Adds support for named indexes
architect/package pull request #92
Opened 2020-10-07 13:08 UTC by anatomic

A first pass at providing a solution for https://github.com/architect/architect/issues/974 which allows a custom index name to be provided as part of the @indexes declaration.

2020-10-07 13:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/architect/package?pullRequest=92) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/architect/package?pullRequest=92) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/architect/package?pullRequest=92) it.</sub>

2020-10-14 17:53 UTC, ryanblock commented
→ https://github.com/architect/architect/issues/974#issuecomment-708562679

2021-01-22 15:21 UTC, anatomic commented
Sorry, had a struggle with time :( I'm going to try and have another look at this..

2021-01-22 15:50 UTC, anatomic commented
Looking over how things have changed since this PR was raised, it looks like it's a more straightforward change to match the suggestion on the original issue however it will require a change in the `inventory` package too. 

@ryanblock does that sound right to you and do you think it's worth pursuing this change or as time has moved on since this change was raised and nobody else has been clamouring for it maybe it isn't needed?

2021-01-22 16:08 UTC, anatomic commented on src/visitors/indexes/get-gsi-name.js
> +  let { indexName, name, partitionKey, partitionKeyType, sortKey } = index
Requires an update to `inventory` to parse `indexName` from the `@indexes` pragma

2021-01-22 16:53 UTC, anatomic commented on src/visitors/indexes/get-gsi-name.js
> +  let { indexName, name, partitionKey, partitionKeyType, sortKey } = index
https://github.com/architect/inventory/pull/13

2021-01-22 19:01 UTC, ryanblock commented
I don't have an opinion about whether folks would like this or not, but it seems like a fine addition! Please note Inventory has complete test coverage in these paths and we need that to continue to be the case before merging.

2021-03-01 20:08 UTC, filmaj requested changes
@anatomic I love it! I would love to see this land. It looks like this was released in inventory 1.2.3. I think all that this PR needs is the bump in the package.json to bump up the inventory version to 1.2.3.

2021-03-02 17:59 UTC, filmaj commented
I've expanded on this branch in a new PR that includes tests and the inventory bump: #103 

Closing this one in favour of the new one.

2021-03-02 17:59 UTC, closed without merging